Some artifacts issues resolved
swarfarm/swarfarm pull request #165
Opened 2020-11-05 20:23 UTC by QuatZo

* Fixed Artifact group counter showing "0 runes" instead of "<num> artifacts"
* Fixed Artifact page title (Runes -> Artifacts)
* Added Artifacts to Monster List
* Added Artifacts to Monster Popover
* Fixed Artifact Popover not having element/archetype logo
* Added Unknown image (couldn't find in static files)
* Added nested groups (by mainstat) in Artifact slot groups

resolves #149 
resolves #154 
resolves #155

2020-11-06 16:24 UTC, PeteAndersen requested changes

2020-11-06 16:24 UTC, PeteAndersen commented on herders/templates/herders/profile/artifacts/inventory.html
> +                                    <div class="panel-body">
This `panel-body` is nested in the `panel-body` div from L54, causing extra padding:

![image](https://user-images.githubusercontent.com/11867035/98386472-112cb500-2005-11eb-9c61-1bc7d8476733.png)

2020-11-06 16:31 UTC, PeteAndersen commented
Looks overall great, but will wait for @deirdresm to have a chance to look at it too before merging

2020-11-06 16:41 UTC, QuatZo commented
Deleted additional padding
![image](https://user-images.githubusercontent.com/48104274/98391722-4eba2e00-2057-11eb-8359-22d9c6af063f.png)

2020-11-09 15:08 UTC, QuatZo commented
I've checked it as a draft since there are some other issues with artifacts I would like to resolve before merging it to master:
* https://swarfarm.com/feedback/143/
* Issue #171

2020-11-09 22:16 UTC, PeteAndersen commented
Needs a migration file committed for the change from IntegerField to FloatField. Will do a full review in a few hours.

2020-11-10 22:13 UTC, QuatZo commented
Commit https://github.com/PeteAndersen/swarfarm/pull/165/commits/440bb65b2383c99b534cfa9ef0677e52b2ad4a38 resolves #172

2020-11-11 16:41 UTC, PeteAndersen commented
All good except one minor issue: Monster stats table doesn't update when adding/removing an artifact on the monster view page. This is handled in `herders/static/herders/js/monster_view.js`, needs a call to `UpdateStats()` added to the `AssignArtifactChoice()` and `UnassignArtifact()` methods.

2020-11-11 17:00 UTC, QuatZo commented
> All good except one minor issue: Monster stats table doesn't update when adding/removing an artifact on the monster view page. This is handled in `herders/static/herders/js/monster_view.js`, needs a call to `UpdateStats()` added to the `AssignArtifactChoice()` and `UnassignArtifact()` methods.

Fixed, works like a charm

2020-11-11 17:41 UTC, PeteAndersen approved these changes

2020-11-11 17:57 UTC, merged